### ISSUE TITLE
Add Details of Instructors

### ISSUE THREAD

**Issue by tbhaxor** [The-Silicon-Valley/mastermindcalls#2]
Add the following details of instructor

1. Name
2. GitHub Account
3. At least one active social account

**Comment by raunakhajela** [comment]
We can add a field with the instructor name which is linked to the GitHub profile. I don't think it makes sense that we share authors' social profiles as some like to keep it private. But if they want to share then in the mastermind call description we can add more author details simple.

**Comment by tbhaxor** [comment]
Ohk atleast add the name of and gh profile of author.
